version: '3.9'
name: go
services:
  lift-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lift-app-server
    working_dir: /target
    restart: unless-stopped
    ports:
      - '8000:8999'
